### ISSUE TITLE
constrain of numbers

### ISSUE THREAD

**Issue by wrx33** [YoongiKim/AutoCrawler#15]
hi, thanks for sharing.
And how to constrain the number of images to download, like I only want to 100 images.
thanks for help

**Comment by YoongiKim** [comment]
Hi.
This problem is little bit hard...
As this program is based on multi treading, I can't share count variables among threads.
And sometimes download fails so we cannot divide task exactly.

So there is only one solution:
```
if len(glob.glob("download/*", recursive=True) >= MAX_COUNT:
    # STOP CRAWLING THE KEYWORD
```
I will add this feature later but if you want to use it you can just implement it.
Thank you.

**Comment by YoongiKim** [comment]
Hi.

**junho-one** solved this issue.

Thank you.
