### ISSUE TITLE
Click time out - //input[@type="button"] when downloading google photos

### ISSUE THREAD

**Issue by ShiratsuyuClassYuudachi** [YoongiKim/AutoCrawler#22]
When running the script , it will try to scoll down pages for one time, but after that the error will keep happening and I can`t get any link. My Chrome version is 84.0.4147.105 and system versin is 5.6.15-1-MANJARO

**Comment by yunkchen** [comment]
+1

**Comment by YoongiKim** [comment]
I couldn't reproduce your error.

But chromedriver version mismatch may produce click failing error.
**I updated chromedriver version from v83 to v84.**
I hope bug fixed.

If the error doesn't fix, please add comment.
Thank you.

**Comment by cs-heibao** [comment]
@YoongiKim 
I've also meet the same problem, and I check the chrome driver Session info: chrome=88.0.4324.96, and the driver in chrome folder is also the corresponding version

**Comment by cs-heibao** [comment]
@YoongiKim 
I've solved the error, I update your project, and then it runs well.but the images all download from naver instead of google, and finally also occur `Click time out - //input[@type="button"]`, I wonder it is the reason that I can not access google browser
```
Downloading car from naver: 375 / 375
Done naver : car
Scrolling down
Click time out - //input[@type="button"]
Refreshing browser...
Click time out - //input[@type="button"]
```
by the way, the maximum picture of one class is limited(for example, I set the keyword 'car', and the download pictures is just 375)

**Comment by YoongiKim** [comment]
Click fail means that program couldn't find the button's html tag.
Google's html code may different in country and website keeps changing to prevent crawling.

You can check the XPATH of button in html code by using developer mode.
![image](https://user-images.githubusercontent.com/38288705/105590177-54611d80-5dd5-11eb-87b6-786b475c35ec.png)

And change in collect_links.py
```self.wait_and_click('//input[@type="button"]')```


Maximum number of picture is not limited basically. the 375 means that crawler only found the 375 image links.

**Comment by cs-heibao** [comment]
@YoongiKim 
the result as follow:

**Comment by jagwoo12** [comment]
혹시 xpath를 추출해서 어떻게 바꾸라는 뜻이실까요?

**Comment by vinson2233** [comment]
In my case, if the keyword I use make google to give ads like this 
![image](https://user-images.githubusercontent.com/33550590/134104228-35db4856-5fa1-4231-b701-649a2c6f1e27.png)

Then the //input[@type="button"] error occur.

So i will try another variant of keyword that won't trigger google ads.

**Comment by 22ema** [comment]
In my case, the number of images was low and there was no button to view more results, so the code below was looping infinitely. After commenting out the exception code, when elem is None, when implemented to pass, it worked normally.

If Execption continues to occur within the wait_and_click() function, the problem seems to be that the wait_and_click() function is continuously called.

![image](https://github.com/YoongiKim/AutoCrawler/assets/39461529/5db2cc28-c83d-45cd-b237-839520be4210)

![image](https://github.com/YoongiKim/AutoCrawler/assets/39461529/64f29b09-6928-4e53-917f-04f342bb9297)

Note please.
